version: "3.7"
services:
  mysql:
    container_name: "mysql_job_interview_db_backend_development"
    image: "mysql/mysql-server:5.6"
    command:
      - mysqld
      - "--init-connect='SET NAMES utf8'"
      - "--collation-server=utf8_general_ci"
      - "--character-set-server=utf8"
      - "--innodb-flush-log-at-trx-commit=0"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql:rw,noexec,nosuid,size=1024m
    volumes:
      - "../database:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_ROOT_PASSWORD=host
      - TZ=Asia/Bangkok
